# Generated by Django 4.2 on 2024-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indian',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
