# Generated by Django 4.2 on 2024-03-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_indian_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indian',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='indian',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
